// swift-tools-version:5.9
//
// GENERATED FILE - DO NOT EDIT BY HAND.
//
// This manifest is generated by the narya-ios release workflow
// (scripts/release-xcframework.sh, invoked by .github/workflows/release.yml)
// and pushed to https://github.com/MithraAI/mithra-ios-sdk on every release.
// Any manual edit is overwritten by the next release; change the generator in
// narya-ios instead.
//
// Version: 1.3.0

import PackageDescription

let package = Package(
    name: "MithraSDK",
    // iOS only: the published XCFrameworks contain iOS device + simulator
    // slices only, so declaring any other platform would resolve and then
    // fail at link time.
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "MithraAnalytics",
            targets: ["MithraAnalytics"]
        ),
        .library(
            name: "MithraAnalyticsNotificationService",
            targets: ["MithraAnalyticsNotificationService"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "MithraAnalytics",
            url: "https://sdk.mithra.com/ios/MithraAnalytics-1.3.0.zip",
            checksum: "ed4d2d41547451711e889f725074ffce97c85ffb35cc5c0e946cb88c2abc927f"
        ),
        .binaryTarget(
            name: "MithraAnalyticsNotificationService",
            url: "https://sdk.mithra.com/ios/MithraAnalyticsNotificationService-1.3.0.zip",
            checksum: "805c00e0827b141d910dc1736390ce8d66bf6e6757e5dea7822abd4f919c76d7"
        ),
    ]
)
