// swift-tools-version:5.9
//
// GENERATED FILE - DO NOT EDIT BY HAND.
//
// This manifest is generated by the narya-ios release workflow
// (scripts/release-xcframework.sh, invoked by .github/workflows/release.yml)
// and pushed to https://github.com/MithraAI/mithra-ios-sdk on every release.
// Any manual edit is overwritten by the next release; change the generator in
// narya-ios instead.
//
// Version: 1.3.1

import PackageDescription

let package = Package(
    name: "MithraSDK",
    // iOS only: the published XCFrameworks contain iOS device + simulator
    // slices only, so declaring any other platform would resolve and then
    // fail at link time.
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "MithraAnalytics",
            targets: ["MithraAnalytics"]
        ),
        .library(
            name: "MithraAnalyticsNotificationService",
            targets: ["MithraAnalyticsNotificationService"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "MithraAnalytics",
            url: "https://sdk.mithra.com/ios/MithraAnalytics-1.3.1.zip",
            checksum: "c11707699a799a05e80b40c63400cd4f769aae3002dee29900cc7b330602acf9"
        ),
        .binaryTarget(
            name: "MithraAnalyticsNotificationService",
            url: "https://sdk.mithra.com/ios/MithraAnalyticsNotificationService-1.3.1.zip",
            checksum: "b8eade787dea859ed9b794ed49475916da00ac1300202f9816fc320ac0b8a559"
        ),
    ]
)
