// swift-tools-version:5.9
//
// GENERATED FILE - DO NOT EDIT BY HAND.
//
// This manifest is generated by the narya-ios release workflow
// (scripts/release-xcframework.sh, invoked by .github/workflows/release.yml)
// and pushed to https://github.com/MithraAI/mithra-ios-sdk on every release.
// Any manual edit is overwritten by the next release; change the generator in
// narya-ios instead.
//
// Version: 1.5.0

import PackageDescription

let package = Package(
    name: "MithraSDK",
    // iOS only: the published XCFrameworks contain iOS device + simulator
    // slices only, so declaring any other platform would resolve and then
    // fail at link time.
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "MithraAnalytics",
            targets: ["MithraAnalytics"]
        ),
        .library(
            name: "MithraAnalyticsNotificationService",
            targets: ["MithraAnalyticsNotificationService"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "MithraAnalytics",
            url: "https://sdk.mithra.com/ios/MithraAnalytics-1.5.0.zip",
            checksum: "5d929f73a98bce8cd26d0e12ba3e08493c6290e3f4dfb8b64dfeaba2127347b7"
        ),
        .binaryTarget(
            name: "MithraAnalyticsNotificationService",
            url: "https://sdk.mithra.com/ios/MithraAnalyticsNotificationService-1.5.0.zip",
            checksum: "0e66f3ac3260a0ed96f09f89223924ed43e150920f7d7a47e32b7b45deb47d7e"
        ),
    ]
)
